site_name: Utilisation de MacBook M1
site_author: Étienne Rivard
site_url: https://m1.professeur.tech
theme:
  name: mkdocs
  nav_style: dark
  custom_dir: custom_theme/

plugins:
    - search

extra_css:
    - css/extra.css

extra_javascript:
  - javascript/linktarget.js


nav:
  - 'Page principale' : 'index.md'
  - 'Installation' :
    - 'GIT' : 'git.md'  
    - 'UTM' : 'utm.md'  
    - 'Windows XP' : 'xp.md'  
  - 'Procédures' :  
    - 'Créer ISO' : 'creer-iso.md'  


markdown_extensions:
    - admonition

docs_dir: 'docs'
site_dir: '~/static'
use_directory_urls: True
